name: topocurve
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.21.1
  - scipy=1.7.1
  - photutils=1.2.0
  - pillow=8.4.0
  - tifffile=2021.10.12
  - scikit-learn=1.0.2
  - rasterio
  - pyproj
  - matplotlib
  - geotiff
  - zarr<2.13
  - numcodecs>=0.13.1,<0.16
  - click
  - sphinx
  - coverage
  - awscli
  - flake8
  - python-dotenv>=0.5.1
  - pip
  - pip:
      - -e .
